// <auto-generated sample/>
// 本文件仅作「生成结果长什么样」的对照，不要当正式导表产物使用。
// 正式文件由 ExcelConfigCompiler 从 Excel 生成后覆盖到你的 ClientCodeFolder。
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using ExcelConfigCompiler.Runtime;

namespace Game.Config
{
    public struct Item
    {
        public int Id;
        public string Name;
        public int Price;
        public int[] Attrs;

        public void Write(ByteWriter writer)
        {
            writer.WriteInt32(Id);
            writer.WriteString(Name);
            writer.WriteInt32(Price);
            writer.WriteInt32Array(Attrs);
        }

        public void Read(ref ByteReader reader)
        {
            Id = reader.ReadInt32();
            Name = reader.ReadString();
            Price = reader.ReadInt32();
            Attrs = reader.ReadInt32Array();
        }

        public void ReadJson(ref JsonReader reader)
        {
            reader.Expect('{');
            if (reader.TryExpect('}')) return;
            while (true)
            {
                string name = reader.ReadPropertyName();
                switch (name)
                {
                    case "Id": Id = reader.ReadInt32(); break;
                    case "Name": Name = reader.ReadString(); break;
                    case "Price": Price = reader.ReadInt32(); break;
                    case "Attrs": Attrs = reader.ReadInt32Array(); break;
                    default: reader.SkipValue(); break;
                }
                if (reader.TryExpect('}')) break;
                reader.Expect(',');
            }
        }
    }

    public static class ItemTable
    {
        public static Item[] Load(byte[] data)
        {
            var reader = new ByteReader(data);
            if (!reader.ReadMagicMatches(BinaryFormat.Magic))
                throw new InvalidDataException("Item.bytes 文件头 Magic 不匹配，文件可能损坏或不是本表的导出结果。");
            int version = reader.ReadInt32();
            if (version != BinaryFormat.CurrentVersion)
                throw new InvalidDataException($"版本不匹配：文件是 v{version}，当前代码是 v{BinaryFormat.CurrentVersion}，请重新导表。");
            int count = reader.ReadInt32();
            var result = new Item[count];
            for (int i = 0; i < count; i++) result[i].Read(ref reader);
            return result;
        }

        public static Item[] LoadJson(string json)
        {
            var reader = new JsonReader(json);
            reader.Expect('[');
            if (reader.TryExpect(']')) return Array.Empty<Item>();
            var list = new List<Item>(64);
            while (true)
            {
                var row = new Item();
                row.ReadJson(ref reader);
                list.Add(row);
                if (reader.TryExpect(']')) break;
                reader.Expect(',');
            }
            return list.ToArray();
        }

        public static Item[] LoadJsonFromFile(string path)
            => LoadJson(File.ReadAllText(path));

        private static Item[] _cache;
        private static Dictionary<int, int> _indexById;

        public static Item[] LoadAndCache(byte[] data)
        {
            _cache = Load(data);
            _indexById = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                _indexById[_cache[i].Id] = i;
            return _cache;
        }

        public static Item[] LoadJsonAndCache(string json)
        {
            _cache = LoadJson(json);
            _indexById = new Dictionary<int, int>(_cache.Length);
            for (int i = 0; i < _cache.Length; i++)
                _indexById[_cache[i].Id] = i;
            return _cache;
        }

        public static Item Get(int id)
        {
            if (_cache == null || _indexById == null)
                throw new InvalidOperationException("ItemTable.Get 之前必须先调用 LoadAndCache(data)。");
            if (_indexById.TryGetValue(id, out var idx)) return _cache[idx];
            throw new KeyNotFoundException($"Item: 找不到 id={id}");
        }

        public static bool TryGet(int id, out Item value)
        {
            value = default;
            if (_cache == null || _indexById == null) return false;
            if (!_indexById.TryGetValue(id, out var idx)) return false;
            value = _cache[idx];
            return true;
        }
    }
}
