using System;
using System.Text;

namespace ExcelConfigCompiler.Compiler
{
    /// <summary>
    /// Schema → C# 源码字符串。
    /// 每个字段直接展开成 reader.ReadXxx() / writer.WriteXxx()，无反射、无 Attribute、AOT/IL2CPP 友好。
    /// 多语言预留：以后要加其它语言，照着这个类的输入输出再写一个 Generator 即可，无需先抽象接口。
    /// </summary>
    public static class CSharpGenerator
    {
        public static string Generate(TableDef table, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"// 由 ExcelConfigCompiler 从 \"{EscapeComment(table.SourceFile)}\" / Sheet \"{table.TableName}\" 生成。");
            sb.AppendLine("// 不要手改这个文件——改 Excel 然后重新导表。");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using ExcelConfigCompiler.Runtime;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            AppendStruct(sb, table);
            sb.AppendLine();
            AppendTableClass(sb, table);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendStruct(StringBuilder sb, TableDef table)
        {
            sb.AppendLine($"    public struct {table.TableName}");
            sb.AppendLine("    {");
            foreach (var f in table.Fields)
                sb.AppendLine($"        public {CSharpType(f.Type)} {f.CSharpName};");

            sb.AppendLine();
            sb.AppendLine("        public void Write(ByteWriter writer)");
            sb.AppendLine("        {");
            foreach (var f in table.Fields)
                sb.AppendLine($"            writer.{WriteMethod(f.Type)}({f.CSharpName});");
            sb.AppendLine("        }");

            sb.AppendLine();
            sb.AppendLine("        public void Read(ref ByteReader reader)");
            sb.AppendLine("        {");
            foreach (var f in table.Fields)
                sb.AppendLine($"            {f.CSharpName} = reader.{ReadMethod(f.Type)}();");
            sb.AppendLine("        }");

            // AOT JSON：零反射，字段名硬编码 switch
            sb.AppendLine();
            sb.AppendLine("        public void ReadJson(ref JsonReader reader)");
            sb.AppendLine("        {");
            sb.AppendLine("            reader.Expect('{');");
            sb.AppendLine("            if (reader.TryExpect('}')) return;");
            sb.AppendLine("            while (true)");
            sb.AppendLine("            {");
            sb.AppendLine("                string name = reader.ReadPropertyName();");
            sb.AppendLine("                switch (name)");
            sb.AppendLine("                {");
            foreach (var f in table.Fields)
                sb.AppendLine($"                    case \"{f.CSharpName}\": {f.CSharpName} = reader.{ReadMethod(f.Type)}(); break;");
            sb.AppendLine("                    default: reader.SkipValue(); break;");
            sb.AppendLine("                }");
            sb.AppendLine("                if (reader.TryExpect('}')) break;");
            sb.AppendLine("                reader.Expect(',');");
            sb.AppendLine("            }");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
        }

        private static void AppendTableClass(StringBuilder sb, TableDef table)
        {
            var idField = table.IdField;
            bool canIndex = idField != null && idField.Type == FieldType.Int32;

            sb.AppendLine($"    public static class {table.TableName}Table");
            sb.AppendLine("    {");

            // Load：纯读取，不建索引
            sb.AppendLine($"        public static {table.TableName}[] Load(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            var reader = new ByteReader(data);");
            sb.AppendLine("            if (!reader.ReadMagicMatches(BinaryFormat.Magic))");
            sb.AppendLine($"                throw new InvalidDataException(\"{table.TableName}.bytes 文件头 Magic 不匹配，文件可能损坏或不是本表的导出结果。\");");
            sb.AppendLine("            int version = reader.ReadInt32();");
            sb.AppendLine("            if (version != BinaryFormat.CurrentVersion)");
            sb.AppendLine("                throw new InvalidDataException($\"版本不匹配：文件是 v{version}，当前代码是 v{BinaryFormat.CurrentVersion}，请重新导表。\");");
            sb.AppendLine("            int count = reader.ReadInt32();");
            sb.AppendLine($"            var result = new {table.TableName}[count];");
            sb.AppendLine("            for (int i = 0; i < count; i++) result[i].Read(ref reader);");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");

            // JSON Load（开发期 / 热更可读）
            sb.AppendLine();
            sb.AppendLine($"        public static {table.TableName}[] LoadJson(string json)");
            sb.AppendLine("        {");
            sb.AppendLine("            var reader = new JsonReader(json);");
            sb.AppendLine("            reader.Expect('[');");
            sb.AppendLine("            if (reader.TryExpect(']')) return Array.Empty<" + table.TableName + ">();");
            sb.AppendLine($"            var list = new List<{table.TableName}>(64);");
            sb.AppendLine("            while (true)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var row = new {table.TableName}();");
            sb.AppendLine("                row.ReadJson(ref reader);");
            sb.AppendLine("                list.Add(row);");
            sb.AppendLine("                if (reader.TryExpect(']')) break;");
            sb.AppendLine("                reader.Expect(',');");
            sb.AppendLine("            }");
            sb.AppendLine("            return list.ToArray();");
            sb.AppendLine("        }");

            sb.AppendLine();
            sb.AppendLine($"        public static {table.TableName}[] LoadJsonFromFile(string path)");
            sb.AppendLine("            => LoadJson(File.ReadAllText(path));");

            if (canIndex)
            {
                sb.AppendLine();
                sb.AppendLine($"        private static {table.TableName}[] _cache;");
                sb.AppendLine("        private static Dictionary<int, int> _indexById;");
                sb.AppendLine();
                sb.AppendLine($"        public static {table.TableName}[] LoadAndCache(byte[] data)");
                sb.AppendLine("        {");
                sb.AppendLine("            _cache = Load(data);");
                sb.AppendLine("            _indexById = new Dictionary<int, int>(_cache.Length);");
                sb.AppendLine("            for (int i = 0; i < _cache.Length; i++)");
                sb.AppendLine($"                _indexById[_cache[i].{idField.CSharpName}] = i;");
                sb.AppendLine("            return _cache;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static {table.TableName}[] LoadJsonAndCache(string json)");
                sb.AppendLine("        {");
                sb.AppendLine("            _cache = LoadJson(json);");
                sb.AppendLine("            _indexById = new Dictionary<int, int>(_cache.Length);");
                sb.AppendLine("            for (int i = 0; i < _cache.Length; i++)");
                sb.AppendLine($"                _indexById[_cache[i].{idField.CSharpName}] = i;");
                sb.AppendLine("            return _cache;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        /// <summary>查询阶段不产生 GC，前提是先调用过 LoadAndCache / LoadJsonAndCache。</summary>");
                sb.AppendLine($"        public static {table.TableName} Get(int id)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (_cache == null || _indexById == null)");
                sb.AppendLine($"                throw new InvalidOperationException(\"{table.TableName}Table.Get 之前必须先调用 LoadAndCache(data)。\");");
                sb.AppendLine("            if (_indexById.TryGetValue(id, out var idx)) return _cache[idx];");
                sb.AppendLine($"            throw new KeyNotFoundException($\"{table.TableName}: 找不到 id={{id}}\");");
                sb.AppendLine("        }");

                sb.AppendLine();
                sb.AppendLine($"        public static bool TryGet(int id, out {table.TableName} value)");
                sb.AppendLine("        {");
                sb.AppendLine("            value = default;");
                sb.AppendLine("            if (_cache == null || _indexById == null) return false;");
                sb.AppendLine("            if (!_indexById.TryGetValue(id, out var idx)) return false;");
                sb.AppendLine("            value = _cache[idx];");
                sb.AppendLine("            return true;");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
        }

        private static string CSharpType(FieldType t) => t switch
        {
            FieldType.Byte => "byte",
            FieldType.SByte => "sbyte",
            FieldType.Int16 => "short",
            FieldType.UInt16 => "ushort",
            FieldType.Int32 => "int",
            FieldType.UInt32 => "uint",
            FieldType.Int64 => "long",
            FieldType.UInt64 => "ulong",
            FieldType.Single => "float",
            FieldType.Double => "double",
            FieldType.Boolean => "bool",
            FieldType.String => "string",
            FieldType.Int32Array => "int[]",
            FieldType.ByteArray => "byte[]",
            FieldType.SingleArray => "float[]",
            FieldType.StringArray => "string[]",
            _ => throw new NotSupportedException(t.ToString()),
        };

        private static string WriteMethod(FieldType t) => t switch
        {
            FieldType.Byte => "WriteByte",
            FieldType.SByte => "WriteSByte",
            FieldType.Int16 => "WriteInt16",
            FieldType.UInt16 => "WriteUInt16",
            FieldType.Int32 => "WriteInt32",
            FieldType.UInt32 => "WriteUInt32",
            FieldType.Int64 => "WriteInt64",
            FieldType.UInt64 => "WriteUInt64",
            FieldType.Single => "WriteSingle",
            FieldType.Double => "WriteDouble",
            FieldType.Boolean => "WriteBoolean",
            FieldType.String => "WriteString",
            FieldType.Int32Array => "WriteInt32Array",
            FieldType.ByteArray => "WriteByteArray",
            FieldType.SingleArray => "WriteSingleArray",
            FieldType.StringArray => "WriteStringArray",
            _ => throw new NotSupportedException(t.ToString()),
        };

        private static string ReadMethod(FieldType t) => t switch
        {
            FieldType.Byte => "ReadByte",
            FieldType.SByte => "ReadSByte",
            FieldType.Int16 => "ReadInt16",
            FieldType.UInt16 => "ReadUInt16",
            FieldType.Int32 => "ReadInt32",
            FieldType.UInt32 => "ReadUInt32",
            FieldType.Int64 => "ReadInt64",
            FieldType.UInt64 => "ReadUInt64",
            FieldType.Single => "ReadSingle",
            FieldType.Double => "ReadDouble",
            FieldType.Boolean => "ReadBoolean",
            FieldType.String => "ReadString",
            FieldType.Int32Array => "ReadInt32Array",
            FieldType.ByteArray => "ReadByteArray",
            FieldType.SingleArray => "ReadSingleArray",
            FieldType.StringArray => "ReadStringArray",
            _ => throw new NotSupportedException(t.ToString()),
        };

        private static string EscapeComment(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
