using System;
using System.Text;

namespace ExcelConfigCompiler.Compiler
{
    /// <summary>
    /// 服务器专属 C# 模板：readonly struct + T[] + 可选 FrozenDictionary 索引。
    /// 与客户端共用同一套 .bytes wire format（字段顺序一致）。
    /// 依赖 net8.0+ 的 System.Collections.Frozen（可用 useFrozenDictionary=false 降级为 Dictionary）。
    /// </summary>
    public static class ServerCSharpGenerator
    {
        public static string Generate(TableDef table, string ns, bool useFrozenDictionary = true)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"// 由 ExcelConfigCompiler [Server] 从 \"{EscapeComment(table.SourceFile)}\" / Sheet \"{table.TableName}\" 生成。");
            sb.AppendLine("// 不要手改这个文件——改 Excel 然后重新导表。");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.IO;");
            if (useFrozenDictionary)
                sb.AppendLine("using System.Collections.Frozen;");
            sb.AppendLine("using ExcelConfigCompiler.Runtime;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            AppendReadonlyStruct(sb, table);
            sb.AppendLine();
            AppendTableClass(sb, table, useFrozenDictionary);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendReadonlyStruct(StringBuilder sb, TableDef table)
        {
            sb.AppendLine($"    public readonly struct {table.TableName}");
            sb.AppendLine("    {");
            foreach (var f in table.Fields)
                sb.AppendLine($"        public readonly {CSharpType(f.Type)} {f.CSharpName};");

            sb.AppendLine();
            sb.AppendLine($"        public {table.TableName}(ref ByteReader reader)");
            sb.AppendLine("        {");
            foreach (var f in table.Fields)
                sb.AppendLine($"            {f.CSharpName} = reader.{ReadMethod(f.Type)}();");
            sb.AppendLine("        }");

            // 可选：与客户端对称的 Write，便于调试/二次导出
            sb.AppendLine();
            sb.AppendLine("        public void Write(ByteWriter writer)");
            sb.AppendLine("        {");
            foreach (var f in table.Fields)
                sb.AppendLine($"            writer.{WriteMethod(f.Type)}({f.CSharpName});");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
        }

        private static void AppendTableClass(StringBuilder sb, TableDef table, bool useFrozenDictionary)
        {
            var idField = table.IdField;
            bool canIndex = idField != null && idField.Type == FieldType.Int32;
            string dictType = useFrozenDictionary ? "FrozenDictionary<int, int>" : "Dictionary<int, int>";

            sb.AppendLine($"    public static class {table.TableName}Table");
            sb.AppendLine("    {");

            sb.AppendLine($"        public static {table.TableName}[] Load(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            var reader = new ByteReader(data);");
            sb.AppendLine("            if (!reader.ReadMagicMatches(BinaryFormat.Magic))");
            sb.AppendLine($"                throw new InvalidDataException(\"{table.TableName}.bytes 文件头 Magic 不匹配，文件可能损坏或不是本表的导出结果。\");");
            sb.AppendLine("            int version = reader.ReadInt32();");
            sb.AppendLine("            if (version != BinaryFormat.CurrentVersion)");
            sb.AppendLine("                throw new InvalidDataException($\"版本不匹配：文件是 v{version}，当前代码是 v{BinaryFormat.CurrentVersion}，请重新导表。\");");
            sb.AppendLine("            int count = reader.ReadInt32();");
            sb.AppendLine($"            var result = new {table.TableName}[count];");
            sb.AppendLine("            for (int i = 0; i < count; i++)");
            sb.AppendLine($"                result[i] = new {table.TableName}(ref reader);");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");

            if (canIndex)
            {
                sb.AppendLine();
                sb.AppendLine($"        private static {table.TableName}[]? _cache;");
                sb.AppendLine($"        private static {dictType}? _indexById;");
                sb.AppendLine();
                sb.AppendLine($"        public static {table.TableName}[] LoadAndCache(byte[] data)");
                sb.AppendLine("        {");
                sb.AppendLine("            _cache = Load(data);");
                if (useFrozenDictionary)
                {
                    sb.AppendLine("            var builder = new Dictionary<int, int>(_cache.Length);");
                    sb.AppendLine("            for (int i = 0; i < _cache.Length; i++)");
                    sb.AppendLine($"                builder[_cache[i].{idField.CSharpName}] = i;");
                    sb.AppendLine("            _indexById = builder.ToFrozenDictionary();");
                }
                else
                {
                    sb.AppendLine("            _indexById = new Dictionary<int, int>(_cache.Length);");
                    sb.AppendLine("            for (int i = 0; i < _cache.Length; i++)");
                    sb.AppendLine($"                _indexById[_cache[i].{idField.CSharpName}] = i;");
                }
                sb.AppendLine("            return _cache;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        /// <summary>查询阶段不产生 GC（返回值拷贝）。需先 LoadAndCache。</summary>");
                sb.AppendLine($"        public static {table.TableName} Get(int id)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (_cache == null || _indexById == null)");
                sb.AppendLine($"                throw new InvalidOperationException(\"{table.TableName}Table 尚未 LoadAndCache。\");");
                sb.AppendLine("            if (_indexById.TryGetValue(id, out var idx))");
                sb.AppendLine("                return _cache[idx];");
                sb.AppendLine($"            throw new KeyNotFoundException($\"{table.TableName}: 找不到 id={{id}}\");");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static bool TryGet(int id, out {table.TableName} value)");
                sb.AppendLine("        {");
                sb.AppendLine("            value = default;");
                sb.AppendLine("            if (_cache == null || _indexById == null) return false;");
                sb.AppendLine("            if (!_indexById.TryGetValue(id, out var idx)) return false;");
                sb.AppendLine("            value = _cache[idx];");
                sb.AppendLine("            return true;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static {table.TableName}[]? Cache => _cache;");
            }

            sb.AppendLine("    }");
        }

        private static string CSharpType(FieldType t) => t switch
        {
            FieldType.Byte => "byte",
            FieldType.SByte => "sbyte",
            FieldType.Int16 => "short",
            FieldType.UInt16 => "ushort",
            FieldType.Int32 => "int",
            FieldType.UInt32 => "uint",
            FieldType.Int64 => "long",
            FieldType.UInt64 => "ulong",
            FieldType.Single => "float",
            FieldType.Double => "double",
            FieldType.Boolean => "bool",
            FieldType.String => "string?",
            FieldType.Int32Array => "int[]?",
            FieldType.ByteArray => "byte[]?",
            FieldType.SingleArray => "float[]?",
            FieldType.StringArray => "string[]?",
            _ => throw new NotSupportedException(t.ToString()),
        };

        private static string WriteMethod(FieldType t) => t switch
        {
            FieldType.Byte => "WriteByte",
            FieldType.SByte => "WriteSByte",
            FieldType.Int16 => "WriteInt16",
            FieldType.UInt16 => "WriteUInt16",
            FieldType.Int32 => "WriteInt32",
            FieldType.UInt32 => "WriteUInt32",
            FieldType.Int64 => "WriteInt64",
            FieldType.UInt64 => "WriteUInt64",
            FieldType.Single => "WriteSingle",
            FieldType.Double => "WriteDouble",
            FieldType.Boolean => "WriteBoolean",
            FieldType.String => "WriteString",
            FieldType.Int32Array => "WriteInt32Array",
            FieldType.ByteArray => "WriteByteArray",
            FieldType.SingleArray => "WriteSingleArray",
            FieldType.StringArray => "WriteStringArray",
            _ => throw new NotSupportedException(t.ToString()),
        };

        private static string ReadMethod(FieldType t) => t switch
        {
            FieldType.Byte => "ReadByte",
            FieldType.SByte => "ReadSByte",
            FieldType.Int16 => "ReadInt16",
            FieldType.UInt16 => "ReadUInt16",
            FieldType.Int32 => "ReadInt32",
            FieldType.UInt32 => "ReadUInt32",
            FieldType.Int64 => "ReadInt64",
            FieldType.UInt64 => "ReadUInt64",
            FieldType.Single => "ReadSingle",
            FieldType.Double => "ReadDouble",
            FieldType.Boolean => "ReadBoolean",
            FieldType.String => "ReadString",
            FieldType.Int32Array => "ReadInt32Array",
            FieldType.ByteArray => "ReadByteArray",
            FieldType.SingleArray => "ReadSingleArray",
            FieldType.StringArray => "ReadStringArray",
            _ => throw new NotSupportedException(t.ToString()),
        };

        private static string EscapeComment(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
